quarkus:
  flyway:
    baseline-on-migrate: true
    clean-at-start: false
    migrate-at-start: true
    out-of-order: false
    validate-migration-naming: true
    default-schema: url_shortener
  datasource:
    db-kind: postgresql

"%dev":
   quarkus:
     datasource:
       devservices:
         enabled: true
         image-name: postgres:14.5
         db-name: url_shortener

logging:
  level:
    root: debug